---
sudo: false
language: node_js
node_js:
- '10'
script:
- npm run lint
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: robert.rossmann@strv.com
  api_key:
    secure: q2v0XYvkPuSZi7WCNp0vEPP0x178xjrMsCPxB7AA3YFnH9jdX63Bqu+TL1IbopkrsxmFCloAYQ4B56K7gZQ7SR58h+MkzutRWU8gW0lqVYMB85920HIe6i620BGSFL8e23yd+8sz9t6ni08ygOmQ5yDDZIT5srepCTMGkIk+W2YEzp5x4vDOZriVTZpu8/Em1tCZqwx4ZNgVIvsjVSsCu+1y1EwwowEYYp+xO7SVIfMRqSaye2AuA4yRMdRBvSlCSllnvjLjptTfwvSspLENoJBkV6alzNr91Nhe0akGM6iZs2akDzxy9aK+1bjB9dxHfphUZr5rpkVBOPV1xR1bbT1WghCJoaLsvAdOhSj9OW03m3hkRzXpy1rjKdfkqtDB9WxKmToFisVJB/rR4wduJdcgLnSU2XiqVyImtnyIYi+987n93JCzTqlLMYGvpta7PaiQIWVcblgWbOBjWXBtXrldUba9mNAoo2d7/gYSFjYKVlbcMaFBr+jSEF7KOs721nCUjFKoYo0c+94cE8xTEQv7u9FNV5aoIzIZ5a2hriIRInIrTU8iVnZ4QyNE8q5Ks/rERGudnqW2EbwC+C5Geo7Bsp8ZlsOiLVdbANhcw2z8qGkb0RREGV+LFikF9ey2Wof98pBeuNaCa37XxkWZxEqVrTrgY8V5OnLN8T35mMQ=
  on:
    tags: true
    repo: strvcom/eslint-config-javascript
